services:
  - type: web
    name: animated-web
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
      - key: PORT
        value: 3000
    autoDeploy: true
